# Generated by Django 5.1.3 on 2024-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1000, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='raiting',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
